### ISSUE TITLE
运行时xls保存的问题怎么解决呢

### ISSUE THREAD

**Issue by Gavin-yzg** [liangoy/easytrader_server_client#1]
报错如下：
dict_values(["<class 'FileNotFoundError'>: [Errno 2] No such file or directory: 'Z:\\\\xls_folder\\\\tmp7kzt0a7_.xls'"])

**Comment by liangoy** [comment]
这个是easytrader的报错，看样子有两个解决方案：
1、因为报错是报文件夹找不到，所以建立Z:\\xls_folder文件夹
2、在证券客户端上修改日志文件的保存地址

**Comment by Gavin-yzg** [comment]
目前这两步都已经做了，还是一样，是不是取数没有取到？但是没看到跳验证码

**Comment by liangoy** [comment]
以前easytrader能成功运行吗？建议先本地运行一下easytrader，排除一下问题。
这个项目并不能解决easytrader自身的报错

**Comment by Gavin-yzg** [comment]
以前单独运行没有，不过我现在重新安装了，没有单独试过，我试试吧

**Comment by Gavin-yzg** [comment]
单机测试是弹了验证码

**Comment by liangoy** [comment]
我测试用海通证券的，按easytrader的教程来做，不会弹验证码

**Comment by Gavin-yzg** [comment]
解决弹验证码的问题后已经没问题了
